### ISSUE TITLE
Guild Subchannels created with wrong permissions.

### ISSUE THREAD

**Issue by Xyaren** [FlussuferOrga/ts-gw2-verifyBot#11]
Subchannes should have the same permissions as parent.

**Comment by ogrady** [comment]
https://github.com/FlussuferOrga/ts-gw2-verifyBot/pull/10 seems to have fixed this? Not sure if you are still actively working on it, so feel free to just close at any time!

**Comment by Xyaren** [comment]
Yep fixed.
