### ISSUE TITLE
i_sort_id for guild groups should range from 1100 to X

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#16]
This attribute determines where the guild group should be displayed in the context menu and should be set upon guild creation as well.

**Comment by Xyaren** [comment]
This also affects the server group menu and order of groups displayed in the side panel in TeamSpeak.

On adding a guild, all groups should be assigned updated sort IDs.

**Comment by Xyaren** [comment]
Fixed in #38
