### ISSUE TITLE
Replace log.warn with log.warning

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#22]
There seems to be at least one instance where the deprecated version is being used:
```
Main.py:67: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn("Unable to locate channel with name '%s'. Sleeping for 10 seconds...", Config.channel_name)
```

Should be replaced everywhere.

**Comment by Xyaren** [comment]
There are no more usages in the current code since the last refactoring 
Closed by 65ffd8bdf4bfc53d475492c681d601638dfd9e59
