### ISSUE TITLE
Make behaviour between CreateGuild and DeleteGuild consistent

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/ts-gw2-verifyBot#32]
CreateGuild accepts a name, a tag, groupname, and a list of contacts as parameters. 
DeleteGuild operates on the name alone and performs a lookup in the GW2 to determine the tag.

This allows users to create invalid guilds, as they are not sanitised through the API in any way, which can not be deleted, since deleting requires a successful lookup. The commands should either 

(1) operate entirely on the API, i.e. removing the tag-parameter from CreateGuild and looking it up. This would require the introduction of a new error code to reflect when a guild could not be created due to the guild not existing. This also implies that the interface for users in Discord will be changed, since the tag-parameter would be dropped, bearing the potential for confusion.
(2) require all information to be passed to both commands. This would require another parameter to be passed to the DeleteGuild command.

**Comment by Xyaren** [comment]
I much prefer Option 1.
Error codes could be removed and replaced with full detailed error messages, returned in the response.
This allows more flexibility and verbose error descriptions.

**Comment by Xyaren** [comment]
Closed by #36
